/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    java
    application
    jacoco
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // Mockito
    testImplementation("org.mockito:mockito-core:5.7.0")
    testImplementation("org.mockito:mockito-junit-jupiter:5.7.0")

    implementation("com.google.guava:guava:32.1.2-jre")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

jacoco {
    toolVersion = "0.8.11"
}

// Configure the test task
tasks.test {
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
    }
    // Make sure Jacoco report runs after tests
    finalizedBy(tasks.jacocoTestReport)
    ignoreFailures = true
}

// Configure Jacoco report
tasks.jacocoTestReport {
    dependsOn(tasks.test) // run tests first
    reports {
        html.required.set(true)
        xml.required.set(false)
        csv.required.set(false)
    }
}

// Optional: make the "check" task depend on Jacoco report
tasks.named("check") {
    dependsOn(tasks.jacocoTestReport)
}

